### PR TITLE
Improve CIs

### PR DESCRIPTION
**Pull request by lambdalisue**
Now CI supports the following environments.

Note that the current (wrong) document shows the minimum supported version for Vim is v8.0.0134 but it seems v8.0.0027 (which is a minimum version for `Vital.System.Job`) is the minimum.

## AppVeyor (Windows + zip)

- An official Vim (latest) for 32bit Windows
- An official Vim (v8.0.0069) for 32bit Windows (Most close to v8.0.0027)
- A Kaoriya Vim (latest) for 32bit Windows
- A Kaoriya Vim (latest) for 64bit Windows
- A Kaoriya Vim (v8.0.0082) for 32bit Windows (Most close to v8.0.0027)
- A Kaoriya Vim (v8.0.0082) for 64bit Windows (Most close to v8.0.0027)

The Vim (latest) points Vim 8.0.0069 and Kaoriya Vim (latest) points Vim 8.0.0134 for now.
It's better to use more recent one for an official Vim but I could not find any compiled version newer than that for Windows.

## Travis (Linux + git)

- An official Vim (HEAD) with +python/+python3 (seems not working)
- An official Vim (v8.0.0027) with +python/+python3 (seems not working)
- An official Neovim (HEAD) with `neovim` client for python/python3 (seems not working)
- An official Neovim (v0.1.7) with `neovim` client for python/python3 (seems not working)

It seems `has('python3')` returns 0 after `has('python')` in Vim.
So Vim with python is only tested.
It seems either `has('python')` nor `has('python3')` returns `0` somehow in Neovim.
I tried several things but I just ended up.
So only the Neovim without python/python3 is tested even the client has been installed.

## Travis (Mac + brew)

- An official Vim (HEAD) with +python3
- An official Vim (stable) with +python3
- An official Neovim (HEAD) with `neovim` client in python/python3 (seems not working)
- An official Neovim (stable) with `neovim` client in python/python3 (seems not working)

While vim provided by `brew` does not support `+python/+python3`, only `+python3` is tested.
Additionally, it seems either `has('python')` nor `has('python3')` returns `0` somehow.
So only the Neovim without python/python3 is tested even the client has been installed.

### CODE REVIEW

**Comment by lambdalisue** [comment]
T R A V I S........ You are so slow man....

**Comment by bimlas** [comment]
Did you forgot to restore your Git username or is there a way to commit from CI?

**Comment by lambdalisue** [comment]
> Did you forgot to restore your Git username or is there a way to commit from CI?

I just forgot to restore...

**Comment by lambdalisue** [comment]
It seems `+python` is not available on Neovim even with `pip install --user neovim`? https://travis-ci.org/lambdalisue/gina.vim/jobs/203744989#L4125

**Comment by lambdalisue** [comment]
https://github.com/neovim/neovim/issues/3396#issuecomment-164007558

> However, when I open nvim while having virtualenv activated, it fails, as packages installed into user site-packages are not visible from virtual environment.
>
> Changing my .nvimrc to point explicitly to system-wide python: let g:python_host_prog="/usr/bin/python" resolved the issue and I was again able using Python based plugins in nvim regardless of any virtualenv being active or not.


https://docs.travis-ci.com/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs

> CI Environment uses separate virtualenv instances for each Python version. System Python is not used and should not be relied on. If you need to install Python packages, do it via pip and not apt.
> 
> If you decide to use apt anyway, note that Python system packages only include Python 2.7 libraries on Ubuntu 12.04 LTS. This means that the packages installed from the repositories are not available in other virtualenvs even if you use the –system-site-packages option.

**Comment by lambdalisue** [comment]
:tada:

**Pull request merged**
