### PR TITLE
[add] github actions

### PR DESCRIPTION
**Pull request by get-me-power**
Hi, @lambdalisue !
I added github actions to check syntax using vint.
Could you check this Pull Request?

### CODE REVIEW

**Comment by get-me-power** [comment]
github actions will work if merged...

**Comment by lambdalisue** [comment]
Thank you for your contribution. But I'd like to move entire CI to Github Action at once.

**Comment by kazukazuinaina** [comment]
Thanks for review.
Should I close this Pull Request once?

**Comment by kazukazuinaina** [comment]
ps, I tried writing test about github actions based on fern.vim.

It is result
> https://github.com/kazukazuinaina/gina.vim/pull/1/checks?check_run_id=433266100

**Comment by get-me-power** [comment]
I close it once.
Thanks for review!

**Pull request closed without merging**
