### PR TITLE
Add components for statusline/tabline

### PR DESCRIPTION
**Pull request by lambdalisue**
## Looks
With lightline.vim, it looks like

screenshot 2017-03-16 13 51 19

With `gina#component#XXXXX#preset('fancy')`.

Note that you don't need lightline.vim. I use it because I could not be bothered 😆 

## Usage

```
# For users who use ASCII only font
echo gina#component#branch#preset()
echo gina#component#status#preset()
echo gina#component#traffic#preset()

# For users who use Non-ASCII available font
echo gina#component#branch#preset('fancy')
echo gina#component#status#preset('fancy')
echo gina#component#traffic#preset('fancy')

# For users who want to control the looks
echo gina#component#branch#local()
echo gina#component#branch#track()

echo gina#component#status#staged()
echo gina#component#status#unstaged()
echo gina#component#status#conflicted()

echo gina#component#traffic#ahead()
echo gina#component#traffic#behind()
```

Any suggestions or comments?

## Known issues

- Untracked files and Ignored files are not shown in status
    - While there is no way to detect adding untracked files/ignored files, this feature will not be implemented
- <del>status is not updated when tracked files are modified</del> (Fixed)

### CODE REVIEW

**Comment by bimlas** [comment]
The signs is `gina#component#status#preset('fancy')` seems to small for me (on Windows, DejaVu Sans h10 font):

nevtelen

**Note**

The screenshot is taken from Gvim. In terminal the plus sign is more visible (using the same font).

**Comment by lambdalisue** [comment]
Thanks for your response. I feel it is a kind personal preference so I think I leave it while users can use `gina#component#status#preset()` instead 👍 

But I don't really have a strong motivation to keep the signs so if you have any alternative ideas for `'fancy'`, I would like to here.

Btw, I chose superscript `+`, `-`, and `"` because 1) these are corresponding to the ASCII one, 2) I felt the numbers are more important than the signs. But as I said, I don't really have strong motivations for that so if there are any better alternatives, I would like to here.

**Comment by bimlas** [comment]
I absolutely agree that the numbers are more important than the signs. A (bit silly) idea, but what do you think about this?

`<` `←` Staged
`>` `→` Unstaged
`#` `≠` Conflicted

Left/right corresponding the logic of `status` (as up/down for up on the server / down in the worktree), and the conflicted sign is visible enough to warn the user.

**Comment by lambdalisue** [comment]
screenshot 2017-03-17 12 01 36
screenshot 2017-03-17 12 02 01

I like using left/right signs 👍 I modified your idea a bit and updated as the screenshots above. What do you think?

**The reason why I changed**

1. I used `«` and `»` instead because 1) I tried but felt `←` and `→` were a bit difficult to distinguish on my environment, 2) Gina uses `<<`/`>>` key mappings to stage/unstage changes
2. I used `x` or `×` because I feel `#` is something rather than `≠` (I know sometime `#` is used to mimic `≠` but even so)

**Comment by bimlas** [comment]
It's the most consistent solution, I like it.

**Comment by bimlas** [comment]
It would be nice to provide a component for the name of the repo (the directory name of it, for example `gina.vim`): I switch between projects quite often without closing Vim (thanks to airblade/vim-rooter) and it would be very useful to know the "current scope" from the statusline.

**Comment by lambdalisue** [comment]
Sounds useful. I'll implement it thanks!

**Comment by bimlas** [comment]
I think the `branch` and `traffic` need to be in `Gina status` too: there's no other way to find out the traffic (as I know), but these functions (aka the statusline). If somebody don't want to use the functions, then (s)he has to open `Gina branch` (for current branch name) and `Gina log --all` (for traffic) to be informed. These infos are part of the `git status` so it would be nice to set the `Gina status` buffer statusline to show it.

**Comment by lambdalisue** [comment]
It would be a different topic. So not on this PR.

**Comment by lambdalisue** [comment]
I'll merge this once I finish writing a document about the components.

**Pull request merged**
