### PR TITLE
Command syntax

### LINKED ISSUE #36: Change the command syntax for {revision} and/or {path}
I think there are some inconsistent behavior in the plugin from the view of a (command line) Git user.

For example `Gina info` invokes `git show`, while `Gina show` is some kind of buffer-related-git-show. I think it would be consistent to swap the command names.

Another thing what I don't understand: why it has to [clean the commit message](https://github.com/lambdalisue/gina.vim/blob/256a3c7a56c9d541f185cfa9ff6e3a26aefcce84/test/gina/command/commit.vimspec#L94) manually (07c177f)? Why don't you leave it to Git to do what already knows? Actually it trims the blank lines at the top of the buffer for me (on Windows, using commit message template via Git `commit.template`config) plus when a new `commit.cleanup` option will be added to Git, you have to write the same function for Gina.

### PR DESCRIPTION
**Pull request by lambdalisue**
Fix #36 The concept of this PR is

> Use **treeish** (`{rev}:{path}`) for command which requires revision and/or path instead of `-- {pathspecs}`

Current gina use `-- {pathspecs}` but it is for **filtering** and not for **specifing** usually.
So this PR fix that *unusual command syntax*.

To make API compatible among each commands, the above concept is applied not only `show` but also `browse`, `compare`, and `diff` which basically do not understand what the **treeish** is in command line.

Additionally, to make API compatible, command which only takes path; namely `chaperon`, `edit`, `patch`, and additionally `log`; were modified as well.

In short, the following command syntax has changed

Previous			| New				| Remarks
------------------------------- | ----------------------------- | -------------------------------------
`Gina browse {rev} -- {path}`	| `Gina browse {treeish}`	| Omit {path} and it opens tree URL
`Gina chaperon -- {path}`	| `Gina chaperon {path}`        |
`Gina compare {rev} -- {path}`	| `Gina compare {treeish}`	| Omit {path} warn user to add `:`
`Gina diff {rev} -- {path}`	| `Gina diff {treeish}`		| Omit {path} show a repository diff
`Gina edit -- {path}`		| `Gina edit {path}`            |
`Gina info {rev} -- {path}`	| `Gina show {rev} -- {path}`	| This case show a commit
`Gina log -- {path}`		| `Gina log {path}`		| This case `<Retur>` opens a content
`Gina log -- {path}`		| `Gina log -- {path}`		| This case `<Retur>` opens a commit
`Gina patch -- {path}`		| `Gina patch {path}`           |
`Gina show {rev} -- {path}`	| `Gina show {treeish}`		| This case show a content

The format of `{treeish}` is `{revision}[:{path}]`. For example

- `{revision}:{path}` is used to specify revision and path
- `{revision}:` is used to specify revision and the path is guessed from the current buffer
- `:{path}` is used to specify path and the revision is guessed from the current buffer
- `:0:{path}` is used to specify path and omit the revision (INDEX)
- `:0:` is used to guess path and omit the revision (INDEX)
- `:` is used to guess path and the revision
- `{revision}` is used to specify revision and omit the path
- `:0` is used to omit the path and revision
- An empty string is used to guess revision and omit the path

### CODE REVIEW

**Comment by lambdalisue** [comment]
I would like to merge this to master and starts documentation....
Could you check the behaviour of this PR? @bimlas

**Comment by lambdalisue** [comment]
Note: I'll merge this tomorrow to get more feedbacks if the test success even you haven't reviewed (I need to move on to a different things from day after tomorrow, that's why)

**Comment by bimlas** [comment]
Tested on e0d0d4a on README.md

### :+1: Works as expected

`Gina browse {treeish}` (Omit {path} and it opens tree URL)
`Gina chaperon {path}`
`Gina compare {treeish}` (Omit {path} warn user to add `:`)
`Gina diff {treeish}` (Omit {path} show a repository diff)
`Gina edit {path}`
`Gina log {path}` (This case `<Retur>` opens a content)
`Gina patch {path}`
`Gina show {treeish}` (This case show a content)

### :-1: Issues

**`Gina log -- {path}` (This case `<Retur>` opens a commit)**
**`Gina show {rev} -- {path}` (This case show a commit)**

Does not set up `&filetype` to `git` in commit view.

Regardless of this tiny issue, Gina just become an (almost) fully flagged replacment of command line Git! :clap: :tada: :relaxed:

**Comment by lambdalisue** [comment]
Fixed. It is going to be merged :+1:

**Comment by lambdalisue** [comment]
New fail...

**Comment by lambdalisue** [comment]
Thanks to CI. The new fail implied the critical issue on gina.vim. It is fixed now.

**Comment by lambdalisue** [comment]
Mac on Travis is really really slow so I just don't wait. Now merged :tada:

**Comment by lambdalisue** [comment]
Note: I leave this branch until tests for Mac on Travis has complete.

**Pull request merged**
