### PR TITLE
Fix #76: Remove bang (!) from scheme

### LINKED ISSUE #76: :Gina qrep! doesn't work
Do:

```
:Gina qrep! foo
```

Result:

```
[gina] git: 'qrep!' is not a git command. See 'git --help'.
[gina]
[gina] Did you mean this?
[gina]  grep
```

### PR DESCRIPTION
**Pull request by bimlas**
Fix #76

### CODE REVIEW

**Comment by bimlas** [comment]
I trying to write the tests, but the second one allways fails:

```diff
diff --git a/test/gina/command/qrep.vimspec b/test/gina/command/qrep.vimspec
index 5d6ef66..19e4979 100644
--- a/test/gina/command/qrep.vimspec
+++ b/test/gina/command/qrep.vimspec
@@ -118,5 +118,22 @@ Describe gina#command#qrep
             \ },
             \])
     End
+
+    It might be called with ! (bang)
+      execute 'edit' fnameescape(slit1.path('A/foo.txt'))
+      let orignal_cursor_position = getpos('.')
+      GinaSync qrep! a
+      Assert Equals(getpos('.'), orignal_cursor_position)
+    End
+
+    It might be called without ! (bang)
+      execute 'edit' fnameescape(slit1.path('A/foo.txt'))
+      GinaSync qrep a
+      let cursor_position = getpos('.')
+      let qf_entry = getqflist()[0]
+      Assert Equals(cursor_position[0], qf_entry['bufnr'])
+      Assert Equals(cursor_position[1], qf_entry['lnum'])
+      Assert Equals(cursor_position[2], qf_entry['col'])
+    End
   End
 End
```

The output is
```
Failures:
  1) gina#command#qrep Use cases might be called without ! (bang)
     Error occurred line:
       5:       Assert Equals(cursor_position[0], qf_entry['bufnr'])
     The equivalent values were expected, but it was not the case.

         expected: 9
              got: 0
```

The cursor position is the same as before `Gina qrep`: `[0, 1, 1, 0]` (initial position: first buffer's very first character).

**Comment by lambdalisue** [comment]
Thanks a lot!

> but the second one allways fails

The first value for `getpos('.')` is always `0` rather than the actual buffer number when `{expr}` is `'.'`. See `:h getpos`

```
							*getpos()*
getpos({expr})	Get the position for {expr}.  For possible values of {expr}
		see |line()|.  For getting the cursor position see
		|getcurpos()|.
		The result is a |List| with four numbers:
		    [bufnum, lnum, col, off]
		"bufnum" is zero, unless a mark like '0 or 'A is used, then it
		is the buffer number of the mark.
```

So could you add that test with that modification? I'll merge this then 👍

**Review by lambdalisue — CHANGES_REQUESTED** [review]
As I commented. Adding test you've suggested is better so please add that 👍

**Comment by bimlas** [comment]
`getcurpos()` seems not to work as expected (see commit message and Themis output).

**EDIT**

The cursor position [can be seen here](https://travis-ci.org/lambdalisue/gina.vim/jobs/219560396#L1494-L1496).

**Comment by bimlas** [comment]
I just corrected the tests, but I think there is an issue with `getcurpos()`: it should return with the buffer number of cursor, but it doesn't.

**Comment by lambdalisue** [comment]
0 is correct. 0 means a current so if you specify '.', 0 is a correct bufnr

**Comment by bimlas** [comment]
Well... Yeah, the cursor is alway in the current window... But it's inconsistent I think, as I explained on [vim/vim#1621 (comment)](https://github.com/vim/vim/issues/1621#issuecomment-292500806).

**Comment by bimlas** [comment]
Anyway: the branch works, tests passing, I think it can be merged.

**Comment by lambdalisue** [comment]
Merged. Thanks!

**Pull request merged**
