### PR TITLE
Yank the hash of commit under the cursor (#88)

### PR DESCRIPTION
**Pull request by bimlas**
Add a new action-group `utils` which stores common functionalities like this.

Open up `blame` or `log`, then choose `utils:yank` from the actions list.

### CODE REVIEW

**Comment by bimlas** [comment]
Just realized that there are builtin actions so I moved the definition from `utils` to those, because it's quite widely used, but I don't know if it's a good idea or not. Using `utils` guaranties that the action will be available only where it makes sense (`blame` for example, but not in `status`), but it adds an inconsistent prefix (`utils`). Declaring in builtins seems to be better, because it exists already, but the action not works in every cases so it's not as general as `echo`.

If you don't like it, I will `reset --hard` to previous commit.

PS.: Sorry for making commits what I will revert, but I though that seeing in action is better than just talking about it.

**Comment by lambdalisue** [comment]
Thanks! Well, Action.vim is a vital module so I would like to remove gina's specific code so

1. Use 'word' or so on instead of 'rev' to remove gina dependency
2. Or add 'utils.vim' to gina what you did previously

**Comment by lambdalisue** [comment]
3. Or add some attribute for yank action and copy rev value on blame or log or whatever.

**Comment by bimlas** [comment]
I removed the last commit because yanking revision is related to Gina. I think it's not general enough to be in a Vital modul, because (as the description of the action says) it operates on **revision** - I cannot imagine another context where it could be useful, only another Git plugin.

Added an option to yank path too (if exists) and assigned to more commands.

**Comment by lambdalisue** [comment]
Let's make this like

- `utils:yank:revision` -- Copy a revision
- `utils:yank:path` -- Copy path
- `utils:yank:treeish` -- Copy revision and path in `{revision}:{path}` format

**Pull request closed without merging**
