### PR TITLE
RFC: Add 'blame' feature

### PR DESCRIPTION
**Pull request by lambdalisue**
I added 'blame' feature. I would like to hear comments before I settle the behaviors.

selection_062

### Syntax:

    :Gina blame [+cmd] [++opt] [{options}] [{treeish}]

### Examples:

    :Gina blame :README.md
    :Gina blame :autoload/gina/process.c -L10,20 -L26,30

### Pros/Cons to vim-gita:

- Pros. Incredibely faster (tested on vim/vim/src/eval.c)
  - vim-gita: approx. 14 s
  - gina.vim: approx.  5 s
- Pros. Better option supports
  - E.g. Annotation limit (-L) was not supported in vim-gita
- Cons. Less visibility
  - vim-gita use pseudo lines to separate each chunks which makes easy to recognize a chunk region
  - gina.vim does not separate chunks for performance reason

### Pros/Cons to vim-fugitive:

- Pros. Good looks
  - vim-fugitive shows a raw format
- Pros. Good navigation
  - <CR> to go the commit or the parent commit
  - <BS> to back
  - j/k to show detail
- Cons. A bit slower (tested on vim/vim/src/eval.c)
  - gina.vim: approx.  5 s
  - fugitive: approx.  3 s

### CODE REVIEW

**Comment by bimlas** [comment]
Very cool! Finally, I can drop Fugitive. :smile: 

My opinion:
- Apply J/K map for Up/Down and `<CR>` to `<C-J>` too (alternatives of each other)
- An idea to map all the H/L & Left/Right to navigate in the blame (go back/go to the commit)
- Move `user $hash` line from the end of the hunk to the beginning - this is displayed for shorter hunks, additional contents (like commit message) should go below this, the date would be on the last line to mark the end of the hunk
- Instead of date (`on 23 Dec, 2008`) it displays `(Invalid)` (note that date format in my country is `YYYY-MM-DD`)
- In an earlier stage there was highlighting to separate the hunks visually - where did it go?

**Comment by prabirshrestha** [comment]
+1 for this feature.

Some suggestions.

- `:Gina blame` should work. Currently I need to always specificy the file with `:Gina blame :%`
- I would prefer the commit hash to be on start of the line instead of after the user name. I'm most likely to copy the hash than the user name.
- Might be have some option to see raw git style blame.

**Comment by lambdalisue** [comment]
1. Up/Down: Sure. I will
2. C-j: I know it is CR in terminal but it is
not equal to CR in GUI so I think I shoul leave it and users can customize
3. H/L: Maybe not. I need to confirm if it's conflict with native mapping but I feel user can customize so it is a bit overkill
4. user/hash line: Make sence. I'll move it
5. Highlight: It was really slow on large file. I would like to highlight if there is a good way
6. Gina blame: That conflict with other command syntax . By the way, you can use Gina blame : instead (% is not necessary)
7. Hash/User: Sure. I will
8. Raw: No while it requires additional parse mech to create action candidates

**Comment by lambdalisue** [comment]
9. date: I'll check and I'll make it configureble

**Comment by lambdalisue** [comment]
@bimlas 

I made it configurable. Could you check what kind of format should become a default while `strftime` depens on the platform so I've no idea what kind of format is available on Windows?

https://github.com/lambdalisue/gina.vim/pull/45/commits/fb2b66ffb8050969a66b8f8fbbcc5801df415086

```
let g:gina#command#blame#timestamper#format1 = '...'
let g:gina#command#blame#timestamper#format2 = '...'
```

**Comment by bimlas** [comment]
Date works as expected without changing anything.

I think the "default" is depends on language (locale?) instead of operating system.

**Comment by lambdalisue** [comment]
I ment "%Y" or so on. I don't know what atoms can be used for all

**Comment by mhartington** [comment]
Hi there! Just to leave my opinion.

I actually prefer the format that comes from fugitive

screen shot 2017-02-27 at 3 11 43 pm


In this case, even though its just the raw output, it's tends to be easier to read and figure out than what gina is producing.

screen shot 2017-02-27 at 3 11 59 pm

**Comment by bimlas** [comment]
@lambdalisue: Well, `strftime('%d %b, %Y')` producing `27 febr., 2017` so the format is the same as for Linux, but it prints the month in my language: for example `echo strftime('%d %b, %Y', 1493669754)
` prints `01 máj., 2017` where `máj.` stands for `május` (May in Hungarian).

**Comment by lambdalisue** [comment]
@mhartington Why `gina-blame` window has line numbers? With `setlocal number`, the chunk is wrapped and difficult to distinguish the chunk.

@bimlas 

> Instead of date (on 23 Dec, 2008) it displays (Invalid) (note that date format in my country is YYYY-MM-DD)

Hum...? Then what did you mean with that?

**Comment by lambdalisue** [comment]
**Note** I pushed by `-f`

**Comment by lambdalisue** [comment]
Hum... The current interface has an issue for a large chunk.

screenshot 2017-02-28 14 55 00

I'll think about this but I may change the current interface to completely different one. If you have any idea, I'm welcome to hear.

**Comment by bimlas** [comment]
I was wrong: not **always** prints `(Invalid)`, but when date is "absolute" (`28 febr., 2017`), `XY ago` works. Tried out on Linux where both form of dates are correct. I will try to fix it (you simply cannot test I think).

Found another issues when blaming [this file](https://github.com/bimlas/home/blame/99bca333bc798e7ebfb1964713fe15386866f851/linux_user.sh):

- [Line 43](https://github.com/bimlas/home/blame/99bca333bc798e7ebfb1964713fe15386866f851/linux_user.sh#L43) is not shown in sidebar, but echoing the commit message
- Sidebar/echo seems to be "disconnected": SHAs in sidebar are absolutely different from echoed messages ([line 13](https://github.com/bimlas/home/blame/99bca333bc798e7ebfb1964713fe15386866f851/linux_user.sh#L13))

screenshot

- Sidebar is shorter then content: content is 62 lines while sidebar is 42

Tested on Windows and Linux too!

**Comment by lambdalisue** [comment]
Wait, I may change the interface so do not try to fix for now

**Comment by lambdalisue** [comment]
I got another issue. I'll fix it before release :+1:

**Comment by bimlas** [comment]
It seems to be some kind of index-related bug because echoed message is changing in different line then sidebar. Example (on the file above, signing the lines where echoed message is changing):

```
87a555af          @BimbaLaszlo <- echoing [gina] uj telepitesi rendszer...
uj telepitesi rendszer        
4f594462          @BimbaLaszlo <- echoing [gina] update
update                        
|
|
|
|
|
|                 on (Invalid)
697c920c          @BimbaLaszlo
bin: Fix missing functions    
87a555af          @BimbaLaszlo <- echoing [gina] bin: Fix missing functions WHICH IS 2 LINES ABOVE
uj telepitesi rendszer        
|                 on (Invalid) <- [gina] uj telepitesi rendszer
ba90ea35          @BimbaLaszlo
!vim: Move minimal (debugging 
) settings to a standalone rc 
|                 on (Invalid)
87a555af          @BimbaLaszlo <- [gina] !vim: Move minimal (debugging) settings to a standalone rc 
uj telepitesi rendszer        
|
|
|
|
|                              <- [gina] uj telepitesi rendszer
|
|
|                 on (Invalid)
f85b86f7          @BimbaLaszlo
git: Rename '.git_template/'  
to '.gitconfig_files/'        
|                 on (Invalid)
223030d8          @BimbaLaszlo
f85b86f7          @BimbaLaszlo
git: Rename '.git_template/?/'
f85b86f7          @BimbaLaszlo
git: Rename '.git_template/'   <- [gina] git: Rename '.git_template/' to '.gitconfig_files/' SHOULD BE 8 LINES ABOVE
to '.gitconfig_files/'        
|
|
|
|
|
...
```

**Comment by bimlas** [comment]
> If you have any idea, I'm welcome to hear.

I think the raw `git blame` output (like Fugitive's blame) + echoing the commit message is OK, maybe colorize the SHAs (same SHA = same color), the currently blamed SHA could be reversed (different background color).

**EDIT**
Fugitive using the first 6 chars of SHA as the color which is a good idea I think.

**Comment by lambdalisue** [comment]
color with sha1 may make the word invisible. e.g. color for sha1 0123456789abcdef... makes really dark color and difficult to see

**Comment by bimlas** [comment]
I thought the same but Gina echoing the SHA too. I think the "grouped view" of commits is more important than some "invisible" SHAs.

Another solution would be to group by time (1/2/3/4 week ago, 1/2/3... month ago) but in this case a lot of commits would use the same color which makes difficult to separate visually.

**EDIT**

Or make the colors of SHA reverse. On the line of the actual (opened) commit make the whole line reverse.

**EDIT**

It's a silly idea, sorry... (reversing dark on the dark doesn't makes it more visible) :disappointed:

**Comment by bimlas** [comment]
Another idea: somehow use Vim's conceal feature to colorize a space character befor SHA, so SHA stays visible, but a colorized 'sign' before it can be used to group.

**Comment by bimlas** [comment]
Concept art:

img

(Imagine that the text is not colored)

**Comment by lambdalisue** [comment]
Aha, you just reached the same idea what I'm tring now (conceal box).

Well, additional that, I'm now considering to built unique color based on sha1 in HLS or HSV color space rather than RGB so that I can contral how dark or bright.

I totally agree with that chunk separation is the most important thing. The raw format is not good for this and it is what I don't like the raw format. So I'll try my best on that.

**Comment by lambdalisue** [comment]
Note. I noticed echoring via jk is slow on old computer (my Mac use Core2duo yet!) so I may drop off that and use CursorHold autocmd instead

**Comment by bimlas** [comment]
What about [HSLuv](http://www.hsluv.org)? It cannotbe too dark/light.

It's OK (CursorHold), if a user is interested in the commit, then stops moving.

**Comment by lambdalisue** [comment]
> What about HSLuv? It cannotbe too dark/light.

Thanks. I didn't know that. But actually I noticed that I cannot make good color for term/cterm with HSL or so on and the calculation cost a bit so I ended up to make a GOOD color.

Instead, now I'm trying to make uniqueness with three colors combination like

```
lambdalisue 2 days ago xxxxxxxxx
lambdalisue 2 days ago xxxyyyxxx

|
v

lambdalisue 2 days ago ▌███   -- The first half block indicate the current, and 3 blocks indicate the sha1
lambdalisue 2 days ago  ███
```

1. In 16 colors cterm, use the first letter to choose color. e.g. `FxxFxxFxx` is `color16`, `color16`, `color16`
2. In 256 colors cterm, use the first two letters to choose color. e.g. `FFxFFxFFx` is `color255`, `color255`, `color255`
3. In gui, use the three letters to chose color. e.g. `FFFFFFFFF` is `#f0f0f0`, `#f0f0f0`, `#f0f0f0`

Additionally, I think I don't need to put SHA1 chars while gina echo as you said. So I directly conceal the SHA1 into three boxes.

**Comment by bimlas** [comment]
Since conceal is used, the sidebar can contain the full echoed message, j/k could be mapped to `nnoremap j :p<CR>j` or similar.

**Comment by bimlas** [comment]
Sorry for the late recognition (didn't had time), but I'm not sure that the tricolor is a good idea. Raw blame is useless because it cannot be recognize connection between the hunks associated to the same commit because the letters/digits have to be compared one by one. If colors are used instead of SHA then it's a bit easier, but it needs the same comparing procedure of the brain. For example here's a concept art about what you wrote above.

IMAGE should be here, but nothing works for me (imgur, photobox, drag-n-drop to this comment, NOTHING :angry: )

The highlighted three lines are easier to seperate via colorized SHAs than tricolored lines.

**Comment by lambdalisue** [comment]
It is WIP but I'm trying something like

**Comment by lambdalisue** [comment]
It seems image service is down. I used dropbox instead.

**Comment by bimlas** [comment]
Oh... I though only the bars will be on the sidebar. With the commit messages it's easier to pair the hunks. Great work! :clap:

**Comment by lambdalisue** [comment]
May be I should use flexible sha1 indicator.

1. Prepare N colors
2. If there are N or less revisions in blame, use a single line
3. If there are N×N or less, use two lines
4. If there are N×N×N or less, use three lines

**Comment by bimlas** [comment]
It would be the best (and simpler), but seems to be resource intensive.

**Comment by bimlas** [comment]
(sorry, have to go, will be back tomorrow)

**Comment by lambdalisue** [comment]
I'm satisfied with this new UI.

**When blame shows revisions less than 16 (single column sha1 indicator)**

selection_064

**When blame shows revisions more than 16x16 and less than 16x16x16 (three columns sha1 indicator)**

selection_065

Any comments for the new UI design? (or behaviour which I have not fixed yet)

**Comment by lambdalisue** [comment]
Note that I omitted

- Author name
- SHA1

While I think when user blame, there are two step

1. Find a chunk which you may need to investigate
2. See what was happen on that chunk (revision)

And (I assumed) the author name or SHA1 is not required for the first step. They are required for the second step but users can hit `<Tab>` to choose `echo` action or `show:commit:above` to investigate.

Additionally, I omitted auto-echo as well while it affected to the performance on my old mac. Users can repeat actions by `.` so

1. Select chunk
2. Hit `<Tab>` and type `echo` then hit `<CR>`
3. Repeat with `.`

seems enough. And also, if users still want some auto-echo, they can define custom mappings.

**Comment by bimlas** [comment]
The new design seems to be cool and intuitive. :+1: 

There are issues for me:

**s:CURRENT_MARK = '▌'**

I think it's not a good idea to use non-ascii character since not all of the fonts can display it. For example FixedSys (Windows' default monospace) shows a `?`, DejaVu Sans Mono 'reversing' it (the right side is colored instead of the left). Set it to `|` or similar, or at least make it configurable.

**`show:commit` shows wrong commit**

For example blaming [autoload/gina/core/writer.vim](https://github.com/lambdalisue/gina.vim/blame/4365ff6880f58dae97d29337a2eaef0011fe3985/autoload/gina/core/writer.vim): `echo` shows the info about the right commit, but `show:commit` shows 803f052 on most of the lines which is absolutely irrevelant to this file (tested on Windows & Linux, without *~/.gitconfig* (renamed it)). Note that the file is moved at [778963c](https://github.com/lambdalisue/gina.vim/commit/778963cebb9bc1a3e99382bf9568f22710ed8c38#diff-c31ebbc9c81e1c0a0bc5bf8df4197639).

*autoload/gina/core/console.vim*  producing the same (and it's not renamed).

**Comment by bimlas** [comment]
Just found the solution of `(Invalid)` date but it's a modification of Vital's DateTime:

The bias (offset from UTC) is stored in a [32bit signed number (`REG_DWORD` type)](https://msdn.microsoft.com/en-us/library/windows/desktop/ms724884(v=vs.85).aspx) in Windows registry even on 64 bit system. From [this thread](http://stackoverflow.com/questions/22689574/how-to-make-vim-handle-64bit-int-number) it seems that Vim itself falls short. Patch:

```diff
Fix date parsing on Windows: (Invalid) date on blame                    
                                                                        
The blame interface shows date like `1 month ago` well, but fails on    
`10 Feb, 2017` format (showing `(Invalid)` instead).                    
                                                                        
The commit fixes it, but it seems that offset has issues too. For       
example if the commit date (and author date) is
`2015-10-25 22:07:41 +0100`, then `26. Oct, 2015` shown.                                     
                                                                        
diff --git a/autoload/vital/_gina/DateTime.vim b/autoload/vital/_gina/DateTime.vim
index 9a56574..fa0135e 100644
--- a/autoload/vital/_gina/DateTime.vim
+++ b/autoload/vital/_gina/DateTime.vim
@@ -43,8 +43,15 @@ function! s:_vital_loaded(V) abort
   if s:Prelude.is_windows()
     let key = 'HKLM\System\CurrentControlSet\Control\TimeZoneInformation'
     let regs = s:Process.system(printf('reg query "%s" /v Bias', key))
+    " REG_DWORD is 32 bit number.
     let time = matchstr(regs, 'REG_DWORD\s*\zs0x\x\+')
-    let s:win_tz = empty(time) ? 0 : time / -s:NUM_MINUTES
+    " If integers are stored on 64 bit in Vim, then it have to be filled up to
+    " get the real value of negative numbers. See `:h limits` -> Range of a
+    " Number variable.
+    if (time =~ '^0xf') && (len(printf('%x', -1)) == 16)
+      let time = or(time, 0xffffffff00000000)
+    endif
+    let s:win_tz = empty(time) ? 0 : str2nr(time, 16) / -s:NUM_MINUTES
   endif

   " default values
```

Please review this and if you agree, I will open a PR on Vital (which I never used yet :smile: ).

**Comment by lambdalisue** [comment]
It's great idea to send PR to vital.vim! Please do it. But note that there are a lot of undocumented rules so you will be asked to follow the rules when you send PR like commit message shall start from a module name (e.g. DateTime: Fix bug on 64bit Vim on Windows). Sorry about this.

**Comment by lambdalisue** [comment]
And prob, you will be asked to make a test for that as well

**Comment by pocari** [comment]
It's cool! but I have a problem.
When blame window was resized, `redraw_content` were not called. so, window had become following state.



Currently, I use resizing vim window as workarround( because `redraw_content` is called on `VimResized`)
Is There way to redraw like `<Plug>(gina-blame-xxxx(redraw?))`

**Comment by lambdalisue** [comment]
That's good idea. I'll make it and prob assign it to C-l in default

**Comment by lambdalisue** [comment]
I thought extend ascii is widely availaule but anway i'll make a mark configurable thanks.

i'll investigate the issue thanks!

**Comment by bimlas** [comment]
How can I `:Vitalize .`? It says `Module Vim.Buffer.Anchor is not found`. I installed Vital.vim - Gina has other dependecies too?

**Comment by lambdalisue** [comment]
Yes.

https://github.com/lambdalisue/vital-System-Job
https://github.com/lambdalisue/vital-Vim-Buffer-Anchor
https://github.com/lambdalisue/vital-Vim-Console
https://github.com/lambdalisue/vital-Vim-Buffer-Opener
https://github.com/lambdalisue/vital-Vim-Window
https://github.com/lambdalisue/vital-Vim-Buffer-ANSI
https://github.com/lambdalisue/vital-Config

But as long as you are fixing `DateTime` module, the above modules are not required.
The required steps are

1. Checkout vim-jp/vital.vim
2. Write test which fail on [test/DateTime.vimspec](https://github.com/vim-jp/vital.vim/blob/master/test/DateTime.vimspec)
3. Execute tests by `themis --target DateTime` (while vital.vim has a lot of test)
4. Fix and confirm with the command above

Good luck 👍

**Comment by lambdalisue** [comment]
**Fixed**

- `redraw_content` is called on `WinLeave`, `WinEnter`, and `VimResized` when `winwidth` has changed
- User can force `redraw_content` by `<Plug>(gina-blame-redraw)` or `<Plug>(gina-blame-C-L)` (`<C-L>` in default)
- User can change current mark with `g:gina#command#blame#formatter#current_mark`
- rev mis-match should be fixed

**Unfixed**

- `DateTime` issue (will be fixed by https://github.com/vim-jp/vital.vim/pull/485)

@bimlas @pocari could you check?

**Comment by bimlas** [comment]
:+1: rev mis-match fixed

Some new issues:
- `nomodeline` should be set for sidebar: `vim: Commit message` drops error
- `nofoldenable` should be set for file buffer: do not close folds

Would be good:
- Blame on the currently blamed content (`<CR>` on the marked line) should set cursor's position to the same line
- Same for first blame: `Gina blame` should set the cursor to the same line where it was

**Comment by pocari** [comment]
@lambdalisue 

> redraw_content is called on WinLeave, WinEnter, and VimResized when winwidth has changed
> User can force redraw_content by <Plug>(gina-blame-redraw) or <Plug>(gina-blame-C-L) (<C-L> in default)

it works 👍

**Comment by lambdalisue** [comment]
> nomodeline ...

I recognized that issue on other commands as well. So I'll fix these on a different PR.

> nofoldenable

True. I'll add that

> Blame on the currently blamed content...

Probably no. `blame:enter` action call `Gina blame` with

1. A commit of the chunk if the commit of the blame is different from the commit of the chunk
2. A **previous** commit of the chunk (namely `xxxxx^` or a parent commit) if the commit of the blame is equal to the commit of the chunk

In case of 1, gina can find an original line of the current line while git detected a content movement as a chunk. So `blame:enter` jump to an original line of the chunk.
In case of 2, gina **never** know what was the original line of the current line because the content did not exist on a **previous** commit. So currently gina **reset** the line and use the first line in this case.

> Same for first blame

It is a bit different topic and I would like to make that but it is a bit complicated.

**Comment by bimlas** [comment]
For 2.: isn't it possible to store the current line number before `blame` and restore after it? I mean the cursor position, not line number of hunk. The hunk is added in the currently blamed commit, so the previous commit's same line is where the hunk will appear. It would be easier to overview the changes of the lines around the hunk if cursor's position would be restored.

**Comment by lambdalisue** [comment]
> The hunk is added in the currently blamed commit, so the previous commit's same line is where the hunk will appear.

Not always. For example

```
Current        Previous
============   ============
 1 aaaaaaaaa   1 aaaaaaaaaa
 2 FOOFOOFOO
 3 FOOFOOFOO
 4 FOOFOOFOO
 5 bbbbbbbbb   2 bbbbbbbbbb
 6 ccccccccc   3 cccccccccc
 7 BARBARBAR
 8 BARBARBAR
 9 BARBARBAR
10 ddddddddd   4 dddddddddd
11 eeeeeeeee   5 eeeeeeeeee
```

In this case

1. Line 2-4 on Current should jumps to Line 2 on Previous. It is what you said
2. Line 7-9 on Current should jumps to Line 4 on Previous. It is NOT what you said (your method leads to Line 7 and it is not what we want)

The example is quite simplified so in this case we can calculate where the line comes from but in real world, there are a lot of additions/deletions/modifications so it would be quite difficult. So I just ended up to line 1 because we will quickly lost where we are with Line 7-9 to Line 7 jump in above example

**Comment by bimlas** [comment]
:+1: You convinced me.

**Comment by lambdalisue** [comment]
I will merge this when I've finish writing the document about this feature.
So let me know if there are any unwilling points or give me your 👍

**Comment by lambdalisue** [comment]
🎉

**Comment by prabirshrestha** [comment]
This is what I see when typing `:Gina blame :`. It is almost impossible to figure out what the text is.

image

If I resize the window it shows the diff marker but doesn't do right align.

image

I'm using vim8 on windows.

**Comment by lambdalisue** [comment]
Hum... It is because of the number columns shown in `gina-blame` buffer.
It is strange that `setlocal nonumber` is applied in `ftplugin/gina-blame.vim`.
I'll check it but could you make a new issue for new discussion?

**Comment by prabirshrestha** [comment]
done. filed a new issue at https://github.com/lambdalisue/gina.vim/issues/51

**Comment by bimlas** [comment]
@lambdalisue:

>`DateTime` issue (will be fixed by https://github.com/vim-jp/vital.vim/pull/485)

Just merged, please revitalize.

**Comment by lambdalisue** [comment]
I will. But I'm bit busy so be patient :+1:

**Comment by lambdalisue** [comment]
@bimlas Sorry for late. I updated vital in master 👍

**Comment by bimlas** [comment]
It says:

```
Error detected while processing function vital#gina#import[4]..<SNR>211_import[11]..<SNR>211__import:
line   18:
E605: Exception not caught: vital: fail to call ._vital_loaded(): vital: module not found: Bitwise
```

It may be my mistake, but the tests passing on Vital. Don't you have to "include" Bitwise module?

**Comment by lambdalisue** [comment]
Oh. It seems that the current DateTime module has wrong dependency. I'll fix it later today.

**Comment by lambdalisue** [comment]
https://github.com/vim-jp/vital.vim/pull/487

**Comment by lambdalisue** [comment]
It should be fixed now

**Pull request merged**
