### PR TITLE
Simplify committing

### LINKED ISSUE #37: Let git to remove commentary
https://github.com/lambdalisue/gina.vim/issues/36#issuecomment-281600690

### PR DESCRIPTION
**Pull request by bimlas**
It's absolutely unnecessary to do anything with the commit message
cleanup, Git will prepare and clean by self.

Previously when there was no COMMIT_EDITMSG exist (case of a newly created/cloned
repository), the error handling try/finally dropped an error about the
missing file, it's fixed now.

I hope it really fixes #37

### CODE REVIEW

**Comment by lambdalisue** [comment]
I'll investigate it after middle of March but quick questions

1. Is :e reload cache correctly? Users may close buffer without commit and opens again a bit later with extra changes. In this case the message part should NOT be changed but comment part

2. Do you have any source that said COMMIT_EDITMSG exsist for this kind of feature? I'm not sure if gina should modify the file or keep

**Comment by lambdalisue** [comment]
I've tested and the confirmed that this PR breaks a feature of caching.

1. Open Vim
2. `:Gina commit --allow-empty`
3. Write a commit message (say, `This is a test message`)
4. Save a cache with `:w`
5. Close the buffer without commit by `:q` and hit `n<CR>`
6. Execute `:Gina commit` again
7. A cached message should be shown but an initial commit message without saved cache is shown with this PR

So without fixing this breaks, I'm not going to approve this PR.

**Review by lambdalisue — CHANGES_REQUESTED** [review]
Please fix the cache feature. Well, I think the current implementation is required for that...

**Comment by bimlas** [comment]
I couldn't find a really better way to commit than the current solution.

What I tried:

- Read the contents of the current `COMMIT_EDITMSG` and store it in a variable (*prev*)
- Create a bare commit message to get the updated diff with `git commit --no-template` and store it (*bare*)
- Delete the lines of *prev* from the line matching the first line of *bare*,  than append the contents of *bare* to it
- On `BuffWrite` write the contents back to `COMMIT_EDITMSG`, thus the saved
  commit message can be continued even after closing Vim and opening again

The diff is updated and the comments are recovered.

Problems:

- After commiting, Git does not removes `COMMIT_EDITMSG`, thus the content of it is never gets cleaned - I don't want to delete the file, because it would affetc Git (or other scripts) behaviour
- I could use some indicators (like `=== COMMITTED ===`) on the last line, but this would be ugly

I think the current solution is better than my so closing the PR, but I don't like that it plays with reflog: it can be destructive in certain situation.

**Pull request closed without merging**
